### ISSUE TITLE
Spelling mistake in License.

### ISSUE THREAD

**Issue by 3rdwiki** [jsebean/IlluminationSoftwareCreator#1]
"IlluminationSoftwareCreator
Illumination Software Creator

Licensing: Illumination Software Creatoris licensed under the GPLv2 license."

Should read:
Licensing: Illumination Software Creator is licensed under the GPLv2 license.

"Creator and is" are joined where they don't need to be.

**Comment by jsebean** [comment]
haha thanks I'll modify it
