### ISSUE TITLE
How do you compile and install this?

### ISSUE THREAD

**Issue by noushad-pp** [jsebean/IlluminationSoftwareCreator#2]
I am using linux ubuntu based distro

**Comment by jsebean** [comment]
Hello there,
Unfortunately I do not know as I didn't write it, I just had a copy of the
source and uploaded. Some assets I believe are missing.

Regards,
-Jonah

**Comment by nottux** [comment]
he says:
> Create your binaries (libraries and the main executable) using the IDE, then copy them into the "install" directory using whatever is the desired directory structure

but i don't know what IDE he is talking about

**Comment by jsebean** [comment]
Realbasic it seems, so whatever IDE that works with that (Xojo?). I have no idea, I'm more a node.js/web guy myself xD

**Comment by VashTheStampede01** [comment]
![jsb](https://user-images.githubusercontent.com/22909956/37862465-211e167e-2f45-11e8-91a0-547108e164a5.png)
okay how do i install this im on u16 lts

**Comment by jsebean** [comment]
@raithunderjet Look into the IDE. You can't just start typing filenames in a shell, none of this is compiled.

**Comment by nottux** [comment]
@raithunderjet you have to learn a lot 2 do m8
